### ISSUE TITLE
Gamla Events för one off saker (säkerhetsgenomgångar o.s.v.) fyller event listan

### ISSUE THREAD

**Issue by larlin** [makerslink/MakersLink-Scheduling#27]
Gamla Events för one off saker (säkerhetsgenomgångar o.s.v.) fyller event listan så att den blir svår att navigera.

Antingen gör så att events går att ta bort eller gör så att listan är filterad som standard och bara visar events som har en sluttid i framtiden.

**Comment by nsc-jens** [comment]
Man vill kanske se events som ligger i nära forntid också. I fall man vill schemalägga ytterligare en workshop eller ett fixarpass och ha en mall att titta på. Eller om man glömt lägga till passen innan perioden tar slut... Men att bara visa framtida event och ha en knapp för att visa alla fungerar förstås bra.

**Comment by larlin** [comment]
Nu har jag gjort en version av detta som visar alla events i nuvarande period. Kom nu på att det kan göra det besvärligt att lägga förlänga events repeat end tider om man glömt göra det. Så ska lägga till några fler alternativ. Men lägger upp detta på beta nu i alla fall.

**Comment by larlin** [comment]
Nu har jag lagt till filter möjligheter för sista perioden, föregående period, ingen filtrering och framtida events. Så nu tycker jag den här är klar.
